FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# COPY data data

# COPY backtest.json .
COPY settings.json .
COPY keys.live.json keys.json
# COPY blankly.json .

COPY db.py .
COPY bot_run_live.py .
COPY bot_core.py .

CMD ["/bin/bash", "-c", "cat bot_run_live.py; python bot_run_live.py"]