FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# COPY data data

# COPY backtest.json .
COPY settings.json .
COPY keys.live.json keys.json
# COPY blankly.json .

COPY builder.py .
COPY utils.py .
COPY bot_footer_live.py .
COPY bot_header.py .

RUN python builder.py live

CMD ["/bin/bash", "-c", "cat bot.py; python bot.py"]