services:
  run_trading:
    build:
      context: ../../
      dockerfile: Dockerfile.backtest
    volumes:
      - ../../data:/usr/src/app/data
      - ../../output:/usr/src/app/output
    environment:
      - PARAMS=rsi_period::int=14